# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1cf215e334dee66c02ac0b1da2fe7e4879573c74d10e720f455a552e2137eeb644e65eeae330ee2671b4a8da4f0d1bc5711da1595b3977e7117880bd948b15a

test:
  secret_key_base: 509db188d8845c024af60198147c624efd297120577564161c8108c1db19747b87adf9ae1d9f50ec3614eba89755e3a36d46649f5b54deb0d68a961f978dc36b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
